# Generated by Django 3.1.1 on 2020-11-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20201105_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
