# Generated by Django 3.1.1 on 2020-11-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menu_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='product',
            new_name='category',
        ),
    ]
