# Generated by Django 3.1.1 on 2020-10-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='event_dates',
            field=models.CharField(max_length=254),
        ),
    ]
