# Generated by Django 3.1.1 on 2020-10-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201015_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='require_breakfast',
            field=models.BooleanField(default=True),
        ),
    ]
