# Generated by Django 3.1.1 on 2020-11-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_room_require_breakfast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
